#!/usr/bin/env bash
# install and configurate load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
echo -e "ENABLED=1\n" | sudo tee -a /etc/default/haproxy
string="frontend http
\tbind *:80
\tmode http
\tdefault_backend web-backend
backend web-backend
\tbalance roundrobin
\tserver 954-web-01 34.73.43.83:80 check
\tserver 954-web-02 104.196.6.178:80 check"
echo -e "$string" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart