#!/usr/bin/env bash
# Nginx likes port 80
sed -i 's/8080/80/g' "/etc/nginx/sites-enabled/default"
sed -i 's/ ipv6only=on//g' "/etc/nginx/sites-enabled/default"
sed -i 's/ ipv6only=on//g' "/etc/nginx/sites-available/default"
service nginx restart
