#!/usr/bin/env bash
# Print 10 times "Holberton School" using a while
i=0
while [ $i -le 9 ];do
    echo "Holberton School";
    if [ $i -eq 8 ]
       then
	   echo "Hi";
    fi
    let "i+=1";
done
