#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10 and
i=1
while [ $i -le 20 ];do
    echo "$i";
    case $i in
	4)
	    echo "bad luck from China";
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy";
	    ;;
    esac
    let "i+=1";
done
